BOARD_TAG = adafruit_circuitplayground_m0
ARDUINO_LIBS = libxsvf SPI
USER_LIB_PATH = ./src

# Uncomment DEBUG and DEBUG_FLAGS lines to build symbols for gdb.
# Note that these seem to result in random hanging when opening the
# serial port, so these should be left off for production builds
# (https://stardot.org.uk/forums/viewtopic.php?f=8&t=19815&start=60#p302481).

# DEBUG=1
# DEBUG_FLAGS=-O0 -g -DDEBUG

include ../../third_party/Arduino-Makefile/Sam.mk
