BOARD_TAG = adafruit_circuitplayground_m0
ARDUINO_LIBS = libxsvf SPI
USER_LIB_PATH = ./src

# Uncomment DEBUG=1 to build symbols for gdb
DEBUG=1
DEBUG_FLAGS=-O0 -g -DDEBUG
# OPTIMIZATION_LEVEL = 2

include ../../third_party/Arduino-Makefile/Sam.mk
